project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "!slides/"
    - "!lesson/"
    - "!content_zips_staging/"
    - "!project_zips_staging/"
    - "!exercises/"
    - "!files/projects/"
  resources:
    - "files/"
    - "projects/"
    - "slides/*.html"
    - "slides/*.pdf"
    - "slides/img/"
    - "slides/libs/"
    - "slides/css/"
    - "slides/*_files/"
  preview:
    port: 3334

execute:
  freeze: auto

bibliography: files/bib/readings.bib
csl: files/bib/chicago-author-date.csl

website:
  title: "CLIL Seminar: Data Science"
  description: "Course materials for ISS Data Science Course at Gakushuin University"
  site-url: "https://timmarchand.github.io/ISS_datasci/"
  repo-url: "https://github.com/timmarchand/ISS_datasci"

  draft-mode: unlinked
  favicon: "/files/favicon-512.png"
  page-navigation: true

  navbar:
    pinned: true
    background: "#1a4d2e"
    right:
      - syllabus.qmd
      - schedule.qmd
      - text: "Content"
        href: content/index.qmd
      # - text: "Lessons"
      #   href: lesson/index.qmd
      - text: "Projects"
        href: project/index.qmd
      - text: "Videos"
        href: video/index.qmd
      - text: "Assignments"
        href: assignment/index.qmd
      - text: "Resources"
        href: resource/index.qmd
      - icon: mortarboard-fill
        href: "https://moodle.univ.gakushuin.ac.jp/course/view.php?id=26121"
        aria-label: Moodle

  sidebar:
    - title: "Content"
      style: "docked"
      search: false
      contents:
        - section: "Overview"
          contents:
            - content/index.qmd
        - section: "Foundations"
          contents:
            - text: "1: Course introduction, data types, R and RStudio"
              file: content/01-content.qmd
            - text: "2: R basics 1 — Vectors, data frames, lists, basic scripts"
              file: content/02-content.qmd
            - text: "3: R basics 2 — Data visualisation"
              file: content/03-content.qmd
            - text: "4: R basics 3: Data wrangling"
              file: content/04-content.qmd
        - section: "Core Concepts"
          contents:
            - text: "5: Visualising probability"
              file: content/05-content.qmd
            - text: "6: Manipulating data 1 — Data project intro"
              file: content/06-content.qmd
            - text: "7: Manipulating data 2"
              file: content/07-content.qmd
            - text: "8: Variable associations 1"
              file: content/08-content.qmd
            - text: "9: Variable associations 2"
              file: content/09-content.qmd
        - section: "Advanced Topics"
          contents:
            - text: "10: Regression modelling 1"
              file: content/10-content.qmd
            - text: "11: Regression modelling 2"
              file: content/11-content.qmd
            - text: "12: Text as data"
              file: content/12-content.qmd
        - section: "Project"
          contents:
            - text: "13: Data project completion and course review"
              file: content/13-content.qmd

    - title: "Lessons"
      contents:
        - section: "Overview"
          contents:
            - lesson/index.qmd
        - section: "Foundations"
          contents:
            - text: "1: Course introduction, data types, R and RStudio"
              file: lesson/01-lesson.qmd
            - text: "2: R basics 1 — Vectors, data frames, lists, basic scripts"
              file: lesson/02-lesson.qmd
            - text: "3: R basics 2 — Data visualisation"
              file: lesson/03-lesson.qmd
            - text: "4: R basics 3: Data wrangling"
              file: lesson/04-lesson.qmd
        - section: "Core concepts"
          contents:
            - text: "5: Visualising probability"
              file: lesson/05-lesson.qmd
            - text: "6: Manipulating data 1 — Data project intro"
              file: lesson/06-lesson.qmd
            - text: "7: Manipulating data 2"
              file: lesson/07-lesson.qmd
            - text: "8: Variable associations 1"
              file: lesson/08-lesson.qmd
            - text: "9: Variable associations 2"
              file: lesson/09-lesson.qmd
        - section: "Advanced topics"
          contents:
            - text: "10: Regression modelling 1"
              file: lesson/10-lesson.qmd
            - text: "11: Regression modelling 2"
              file: lesson/11-lesson.qmd
            - text: "12: Text as data"
              file: lesson/12-lesson.qmd
            - text: "13: Data project completion and course review"
              file: lesson/13-lesson.qmd

    - title: "Projects"
      contents:
        - section: "Overview"
          contents:
            - project/index.qmd
        - section: "Problem Sets"
          contents:
            - project/02-ps.qmd
            - project/03-ps.qmd
            - project/04-ps.qmd
            - project/05-ps.qmd
            - project/06-ps.qmd
            - project/final-project.qmd

    - title: "Videos"
      contents:
        - section: "Overview"
          contents:
            - video/index.qmd
        - section: "Foundations"
          contents:
            - text: "1: Course introduction, data types, R and RStudio"
              file: video/01-video.qmd
            - text: "2: R basics 1 — Vectors, data frames, lists, basic scripts"
              file: video/02-video.qmd
            - text: "3: R basics 2 — Data visualisation"
              file: video/03-video.qmd
            - text: "4: R basics 3: Data wrangling"
              file: video/04-video.qmd
        - section: "Core concepts"
          contents:
            - text: "5: Visualising probability"
              file: video/05-video.qmd
            - text: "6: Manipulating data 1 — Data project intro"
              file: video/06-video.qmd
            - text: "7: Manipulating data 2"
              file: video/07-video.qmd
            - text: "8: Variable associations 1"
              file: video/08-video.qmd
            - text: "9: Variable associations 2"
              file: video/09-video.qmd
        - section: "Advanced topics"
          contents:
            - text: "10: Regression modelling 1"
              file: video/10-video.qmd
            - text: "11: Regression modelling 2"
              file: video/11-video.qmd
            - text: "12: Text as data"
              file: video/12-video.qmd
            - text: "13: Data project completion and course review"
              file: video/13-video.qmd

    - title: "Assignments"
      contents:
        - section: "Overview"
          contents:
            - assignment/index.qmd
        - section: "Exercises"
          contents:
            - text: "1: Course introduction, data types, R and RStudio"
              file: assignment/01-exercise.qmd
            - text: "2: R basics 1"
              file: assignment/02-exercise.qmd
            - text: "3: R basics 2"
              file: assignment/03-exercise.qmd
            - text: "4: R basics 3"
              file: assignment/04-exercise.qmd
            - text: "5: Visualising probability"
              file: assignment/05-exercise.qmd
            - text: "6: Manipulating data 1"
              file: assignment/06-exercise.qmd
            - text: "7: Manipulating data 2"
              file: assignment/07-exercise.qmd
            - text: "8: Variable associations 1"
              file: assignment/08-exercise.qmd
            - text: "9: Variable associations 2"
              file: assignment/09-exercise.qmd
            - text: "10: Regression modelling 1"
              file: assignment/10-exercise.qmd
            - text: "11: Regression modelling 2"
              file: assignment/11-exercise.qmd
            - text: "12: Text as data"
              file: assignment/12-exercise.qmd
            - text: "13: Data project completion"
              file: assignment/13-exercise.qmd

    - title: "Resources"
      contents:
        - section: "Resources"
          contents:
            - resource/index.qmd
            - resource/r.qmd
            - resource/install.qmd
            - resource/markdown.qmd
            - resource/quarto.qmd
            - resource/pipes.qmd
            - resource/unzipping.qmd

page-footer:
  left: |
    Content {{< fa brands creative-commons >}} 2026 by [Tim Marchand](your_url) <br>
    Adapted from [Andrew Heiss's Data Visualization course](https://datavizsp26.classes.andrewheiss.com/)
  right: |
    Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
    [View the source at {{< fa brands github >}} GitHub]({{< var course.github >}})

format:
  html:
    include-before-body: html/goatcounter.html
    theme:
      - litera
      - html/custom.scss
    toc: true
    highlight-style: monokai

language:
  draft: "This is a draft—the full FAQ post isn't finished yet."
