---
title: "UN Voting Patterns"
subtitle: "Building a ggplot layer by layer"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      ratio: "16:9"
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
```{r setup, include=FALSE}
library(tidyverse)
library(flipbookr)
library(scales)
library(unvotes)

knitr::opts_chunk$set(
  fig.width = 9,
  fig.height = 5,
  fig.retina = 2,
  message = FALSE,
  warning = FALSE
)

us_uk_turkey_votes <- un_votes %>%
  filter(country %in% c("United States", "United Kingdom", "Turkey")) %>%
  inner_join(un_roll_calls, by = "rcid") %>%
  inner_join(un_roll_call_issues, by = "rcid") %>%
  mutate(year = year(date)) %>%
  group_by(country, year, issue) %>%
  summarize(
    percent_yes = mean(as.character(vote) == "yes"),
    .groups = "drop"
  )
```

---
```{r un_plot, include=FALSE}
us_uk_turkey_votes %>%
  ggplot() +
  aes(x = year) +
  aes(y = percent_yes) +
  aes(color = country) +
  geom_point(alpha = 0.4) +
  geom_smooth(method = "loess", se = FALSE) +
  facet_wrap(~issue) +
  labs(
    title = "Percentage of 'Yes' votes in the UN General Assembly",
    subtitle = "1946 to 2019",
    y = "% Yes",
    x = "Year",
    color = "Country"
  ) +
  scale_y_continuous(labels = label_percent())
```

`r chunk_reveal("un_plot", break_type = "auto")`

---

# Key takeaways

- The US votes "Yes" less frequently than the UK and Turkey on most issues
- All three countries show distinct trends over time
- Human rights and colonialism show the most divergence
