---
title: Interactive lessons
format: html
engine: knitr
filters:
  - webr
webr:
  packages:
    - ggplot2
    - dplyr
    - tidyr
    - readr
    - scales
    - broom
    - gapminder
  cell-options:
    editor-font-scale: 0.8
    fig-width: 7
    fig-height: 4.3
    out-width: "100%"
---

Each class session has an interactive lesson that you will work through ***after*** doing the readings. These lessons are a central part of the class—they will teach you how to use R and the tidyverse to work with, analyse, and visualise data.

Interactive code sections look like this. Make changes in the text box and click on the green "Run Code" button to see the results. Sometimes there will be a tab with a hint or solution.

:::: {.callout-important}
### Your turn
Modify the code here to show only countries in Asia, and change the variable on the x-axis to `lifeExp`.

::: {.panel-tabset}
## {{< fa code >}}&ensp;Interactive editor

```{webr-r}
gapminder_filtered <- gapminder |>
  filter(year == 2007)

ggplot(data = gapminder_filtered,
       mapping = aes(x = gdpPercap, y = pop, 
                     color = continent)) +
  geom_point() + 
  scale_x_log10(labels = scales::dollar_format(accuracy = 1)) +
  scale_y_continuous(labels = scales::label_comma()) +
  scale_color_viridis_d(option = "plasma") +
  labs(x = "GDP per capita", y = "Population",
       title = "Exploring the Gapminder dataset",
       subtitle = "142 countries; 2007 only",
       caption = "Source: The Gapminder Project",
       color = "Continent") +
  theme_bw()
```

## {{< fa lightbulb >}}&ensp;Hint

**Hint:** You'll want to filter by `continent == "Asia"` when creating `gapminder_filtered`, and change `x = gdpPercap` to `x = lifeExp` in the `aes()` call. You may also want to remove the `scale_x_log10()` line since life expectancy doesn't need a log scale.

:::
::::

If you're curious how this works, each interactive code section uses [the amazing {quarto-webr} package](https://quarto-webr.thecoatlessprofessor.com/) to run R directly in your browser—no installation needed!
